watersprinkler/waterapp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'waterapp'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('about', views.about),
	path('services', views.services.as_view(), name = 'services'),
	path('introduce', views.introduce),
    path('agree', views.agree, name = 'agree'),
	path('login/', auth_views.login, {'template_name': 'waterapp/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': 'login'}, name='logout'),
    path('accounts/signup/', views.signup.as_view(), name='signup'),
  	path('post_list', views.postLV.as_view(), name='post_list'),
    path(r'post/(<pk>\d+)/', views.post_detail, name='post_detail'),
    path(r'post/new/', views.post_new, name='post_new'),
    path(r'post/(<pk>\d+)/edit/', views.post_edit, name='post_edit'),
    path(r'post/(<pk>\d+)/remove/', views.post_remove, name='post_remove'),
    path(r'comment/(<pk>\d+)/remove/', views.comment_remove, name='comment_remove'),
    path(r'comment/(<pk>\d+)/edit/', views.comment_edit, name='comment_edit'),
    path('post1_list', views.post1LV.as_view(), name='post1_list'),
    path(r'post1/(<pk>\d+)/', views.post1_detail, name='post1_detail'),
    path(r'post1/new/', views.post1_new, name='post1_new'),
    path(r'post1/(<pk>\d+)/edit/', views.post1_edit, name='post1_edit'),
    path(r'post1/(<pk>\d+)/remove/', views.post1_remove, name='post1_remove'),
    path(r'comment1/(<pk>\d+)/remove/', views.comment1_remove, name='comment1_remove'),
    path(r'comment1/(<pk>\d+)/edit/', views.comment1_edit, name='comment1_edit'),
    path('post2_list', views.post2LV.as_view(), name='post2_list'),
    path(r'post2/(<pk>\d+)/', views.post2_detail, name='post2_detail'),
    path(r'post2/new/', views.post2_new, name='post2_new'),
    path(r'post2/(<pk>\d+)/edit/', views.post2_edit, name='post2_edit'),
    path(r'post2/(<pk>\d+)/remove/', views.post2_remove, name='post2_remove'),
    path(r'comment2/(<pk>\d+)/remove/', views.comment2_remove, name='comment2_remove'),
    path(r'comment2/(<pk>\d+)/edit/', views.comment2_edit, name='comment2_edit'),
    path(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', views.activate, name = 'activate'),
    path(r'duplcheck', views.DuplicationCheck.as_view(), name='duplcheck'),
    path(r'password/', views.change_password, name='change_password'),
    path(r'password_reset/', views.PasswordResetView.as_view(),{'post_reset_redirect': '/password_reset/done/'} ,name='password_reset'),
    path(r'password_reset/done/',  views.password_reset_done,name='password_reset_done'),
    path(r'reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view() ,name='password_reset_confirm'),
    path(r'reset/done/',views.password_reset_complete , name='password_reset_complete')
]

watersprinkler/watersprinkler/urls.py
from django.contrib import admin
from django.urls import path, include
from waterapp import views as waterapp_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('waterapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG: # setting.py의 DEBUG = True인 경우
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

watersprinkler/waterapp/forms.py
# study/forms.py
from django import forms
from .models import Post, Comment, Post1, Comment1, Post2, Comment2
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django_summernote import fields as summer_fields

class PasswordResetRequestForm(forms.Form):
    email_or_username = forms.CharField(label=("Email Or Username"), max_length=254)

class PostForm(forms.ModelForm):

   class Meta:
        model = Post
        fields = ['title', 'content']
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text' : forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': '댓글을 입력해주세요.'}),
        }

class Post1Form(forms.ModelForm):

   class Meta:
        model = Post1
        fields = ['title', 'content']
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
        }


class Comment1Form(forms.ModelForm):

    class Meta:
        model = Comment1
        fields = ('text',)
        widgets = {
            'text' : forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': '댓글을 입력해주세요.'}),
        }


class Post2Form(forms.ModelForm):

   class Meta:
        model = Post2
        fields = ['title', 'content']
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
        }


class Comment2Form(forms.ModelForm):

    class Meta:
        model = Comment2
        fields = ('text',)
        widgets = {
            'text' : forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': '댓글을 입력해주세요.'}),
        }


class CreateUserForm(UserCreationForm):
    use = forms.BooleanField(
        required=False,
        initial=True,
        label = '',
        widget = forms.HiddenInput()
        )
    infor = forms.BooleanField(
        required=False,
        initial=True,
        label = '',
        widget = forms.HiddenInput()
        )
    name = forms.CharField(
        required=True,
        label = "이름",
        widget = forms.TextInput(attrs={ 'class': 'form-control1', 'placeholder': '이름을 입력해주세요'})
        )
    email = forms.EmailField(
        required=True,
        label="이메일",
        widget = forms.TextInput(attrs={'class': 'form-control1', 'placeholder': '이메일 주소를 입력해주세요' ,'id':'email'}),
        )
    username = forms.CharField(
        required=True,
        label="ID",
        widget = forms.TextInput(attrs={'class': 'form-control1', 'placeholder': 'ID를 입력해주세요','id':'idid'}),
        )

    password1 = forms.CharField(
        required=True,
        label="비밀번호",
        widget = forms.PasswordInput(attrs={'class': 'form-control1', 'placeholder': '숫자와 문자를 포함해 8자리 이상을 입력해주세요','id':'password1'}),
        )

    password2 = forms.CharField(
        required=True,
        label="비밀번호 확인",
        widget = forms.PasswordInput(attrs={'class': 'form-control1', 'placeholder': '같은 비밀번호를 다시 입력해주세요.' ,'id':'password2'}),
        )

    class Meta:
        model = User
        fields = ( 'use', 'infor','name' ,'username', 'email', 'password1', 'password2')
        widgets = {
            'username' : forms.TextInput(attrs={'class': 'form-control', 'help_text': ''}),
            'use' : forms.HiddenInput(),
            'infor' : forms.HiddenInput(),
        }

watersprinkler/waterapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, update_session_auth_hash, get_user_model
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth.models import User
from django.utils import timezone
from django.views.generic import ListView
from .models import Post, Comment, Post1, Comment1, Post2, Comment2, Constructionpost, TOS
from .forms import PostForm, CommentForm, CreateUserForm, Post1Form, Comment1Form, Post2Form, Comment2Form
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect, QueryDict
from django.views import View
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.core.mail import mail_managers, send_mail,EmailMessage
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text
from django.conf import settings
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect

UserModel = get_user_model()



def index(request):
	return render(request, 'waterapp/index.html')


def about(request):
	return render(request, 'waterapp/about.html')

class services(ListView):
    model = Constructionpost
    template_name = 'waterapp/services.html'
    paginate_by = 9

    def get_queryset(self):
        qs = Constructionpost.objects.all()
        q = self.request.GET.get('q', '') # GET request의 get 인자중에 q 가 있으면 가져오고, 없으면 빈 문자열

        if q:
            qs = qs.filter(title__icontains=q)

        return qs

def introduce(request):
	return render(request, 'waterapp/introduce.html')


def post(request):
	return render(request, 'waterapp/post.html')


def agree(request):
    toss = TOS.objects.all()

    return render(request, 'waterapp/agree.html', {'toss':toss})

def password_reset_done(request):
    return render(request, 'waterapp/password_reset_done.html')

def password_reset_complete(request):
    return render(request, 'waterapp/password_reset_complete.html')

class signup(View):


    def get(self, request):
        if request.user.is_authenticated:
            return redirect("waterapp:index")
        form = CreateUserForm()
        return render(request, 'waterapp/signup.html', {'form':form})

    def post(self, request):

        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('waterapp/acc_active_email.html',{
                'user':user, 'domain':current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':account_activation_token.make_token(user),
                })
            mail_subject = '계정을 활성화 시켜 주세요.'
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to= [to_email])
            email.send()
            return render(request, 'waterapp/confirm_email_sent.html')

        print(form.errors)


class postLV(ListView):
	model = Post
	template_name = 'waterapp/post_list.html'
	paginate_by = 7

	def get_queryset(self):
		qs = Post.objects.all()
		q = self.request.GET.get('q', '') # GET request의 get 인자중에 q 가 있으면 가져오고, 없으면 빈 문자열

		if q:
			qs = qs.filter(title__icontains=q)

		return qs


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        if request.user.id == None:
            return redirect('login')
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
        return redirect('waterapp:post_detail', pk=post.pk)
    else:
        form = CommentForm()
        return render(request, 'waterapp/post_detail.html', {'post':post, 'form':form})

@login_required
def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return redirect(post)
	else:
		form = PostForm()
	return render(request, 'waterapp/post_new.html', {'form': form})


@login_required
def post_edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES, instance=post)
		if form.is_valid():
			post = form.save()
			return redirect(post)

	else:
		if post.author == request.user:
			form = PostForm(instance=post)
			return render(request, 'waterapp/post_edit.html', {'form':form})
		else:
			return render(request, 'waterapp/warning.html')


@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author == request.user:
        post.delete()
        return redirect('waterapp:post_list')
    else:
        return render(request, 'waterapp/warning.html')



@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.author == request.user:
        post_pk = comment.post.pk
        comment.delete()
        return redirect('waterapp:post_detail', pk=post_pk)
    else:
        return render(request, 'waterapp/warning.html')


@login_required
def comment_edit(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = get_object_or_404(Post, pk=comment.post.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.created_date = timezone.now()
            comment.save()
        return redirect('waterapp:post_detail', pk=post.pk)

    else:
        form_edit = CommentForm(instance=comment)
        return render(request, 'waterapp/post_detail.html', {'post':post, 'form_edit':form_edit, 'pk':comment.pk})




class post1LV(ListView):
    model = Post1
    template_name = 'waterapp/post1_list.html'
    paginate_by = 7

    def get_queryset(self):
        qs = Post1.objects.all()
        q = self.request.GET.get('q', '') # GET request의 get 인자중에 q 가 있으면 가져오고, 없으면 빈 문자열

        if q:
            qs = qs.filter(title__icontains=q)

        return qs


def post1_detail(request, pk):
    post = get_object_or_404(Post1, pk=pk)
    if request.method == "POST":
        if request.user.id == None:
            return redirect('login')
        form = Comment1Form(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
        return redirect('waterapp:post1_detail', pk=post.pk)
    else:
        form = Comment1Form()
        return render(request, 'waterapp/post1_detail.html', {'post':post, 'form':form})

@login_required
def post1_new(request):
    if request.method == "POST":
        form = Post1Form(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(post)
    else:
        form = Post1Form()
    return render(request, 'waterapp/post1_new.html', {'form': form})


@login_required
def post1_edit(request, pk):
    post = get_object_or_404(Post1, pk=pk)
    if request.method == 'POST':
        form = Post1Form(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect(post)

    else:
        if post.author == request.user:
            form = Post1Form(instance=post)
            return render(request, 'waterapp/post1_edit.html', {'form':form})
        else:
            return render(request, 'waterapp/warning.html')


@login_required
def post1_remove(request, pk):
    post = get_object_or_404(Post1, pk=pk)
    if post.author == request.user:
        post.delete()
        return redirect('waterapp:post1_list')
    else:
        return render(request, 'waterapp/warning.html')



@login_required
def comment1_remove(request, pk):
    comment = get_object_or_404(Comment1, pk=pk)
    if comment.author == request.user:
        post_pk = comment.post.pk
        comment.delete()
        return redirect('waterapp:post1_detail', pk=post_pk)
    else:
        return render(request, 'waterapp/warning.html')


@login_required
def comment1_edit(request, pk):
    comment = get_object_or_404(Comment1, pk=pk)
    post = get_object_or_404(Post1, pk=comment.post.id)

    if request.method == "POST":
        form = Comment1Form(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.created_date = timezone.now()
            comment.save()
        return redirect('waterapp:post1_detail', pk=post.pk)

    else:
        form_edit = Comment1Form(instance=comment)
        return render(request, 'waterapp/post1_detail.html', {'post':post, 'form_edit':form_edit, 'pk':comment.pk})



class post2LV(ListView):
    model = Post2
    template_name = 'waterapp/post2_list.html'
    paginate_by = 7

    def get_queryset(self):
        qs = Post2.objects.all()

watersprinkler/waterapp/templates/waterapp/confirm_email_sent.html
<h1>"등록하신 이메일의 메일함을 확인하십시오"</h1>

watersprinkler/waterapp/templates/waterapp/post1_detail.html
{% load staticfiles %}
<!DOCTYPE HTML>
<!--
  Aesthetic by gettemplates.co
  Twitter: http://twitter.com/gettemplateco
  URL: http://gettemplates.co
-->
<html>
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>금수강산(용수공급 도로살수)</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Free HTML5 Website Template by gettemplates.co" />
  <meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
  <meta name="author" content="gettemplates.co" />

    <!-- Facebook and Twitter integration -->
  <meta property="og:title" content=""/>
  <meta property="og:image" content=""/>
  <meta property="og:url" content=""/>
  <meta property="og:site_name" content=""/>
  <meta property="og:description" content=""/>
  <meta name="twitter:title" content="" />
  <meta name="twitter:image" content="" />
  <meta name="twitter:url" content="" />
  <meta name="twitter:card" content="" />

  <link href="https://fonts.googleapis.com/css?family=Merriweather:300,400|Montserrat:400,700" rel="stylesheet">
  
<!-- Animate.css -->
  <link rel='{% static "stylesheet" href="css/animate.css" %}'>
  <!-- Icomoon Icon Fonts-->
  <link rel='{% static "stylesheet" href="css/icomoon.css" %}'>
  <!-- Themify Icons-->
  <link rel='{% static "stylesheet" href="css/themify-icons.css" %}'>
  <!-- Bootstrap  -->
  <link rel="stylesheet" href='{% static "css/bootstrap.css" %}'>

  <!-- Owl Carousel  -->
  <link rel="stylesheet" href='{% static "css/owl.carousel.min.css" %}'>
  <link rel="stylesheet" href='{% static "css/owl.theme.default.min.css" %}'>

  <!-- Theme style  -->
  <link rel="stylesheet" href='{% static "css/style.css" %}'>

  <!-- Modernizr JS -->
  <script src='{% static "js/modernizr-2.6.2.min.js"%} '></script>
  <!-- FOR IE9 below -->
  <!--[if lt IE 9]>
  <script src="js/respond.min.js"></script>
  <![endif]-->
  </head>
  <body>
    
  <div class="gtco-loader"></div>
  
  <div id="page">

    <nav class="gtco-nav" role="navigation">
      <div class="gtco-container">
        
        <div class="row">
        <div class="col-sm-2 col-xs-12">
            <div id="gtco-logo"><a href="/"><img src='{% static "images/mark.jpeg"%}'></a></div>
          </div>
          <div class="col-xs-10 text-right menu-1">
            <ul>
              <a href="/introduce">회사 소개</a></li>
              <li><a href="/about">주요 업무</a></li>
              <li><a href='{% url "waterapp:services"%}'>현장 갤러리</a></li>
              {% if user.is_authenticated %}
              <li><a href='{% url "waterapp:post_list"%}'>구인. 구직</a></li>
              <li><a href='{% url "waterapp:post1_list"%}'>팝니다. 삽니다</a></li>
              <li class="active"><a href='{% url "waterapp:post2_list"%}'>블랙리스트</a></li>
              {% else %}
              {% endif %}
            </ul>
          </div>
        </div>
        
      </div>
    </nav>
    <div style="float: right;padding-right: 170px">
  
      {% if user.is_authenticated %}
        {{ user.username }}님 환영합니다!!   <a href="{% url 'waterapp:logout' %}">로그아웃</a>
      {% else %}
        <a href="{% url 'login' %}">로그인</a> / <a href="{% url 'waterapp:agree' %}">회원가입</a>
      {% endif %}
   
  </div>
  <br>
  


  <div class="post-set-btn">
    <div style="padding: 170px">
    <div class="btn-wrap">
      <div style="padding-bottom: : 170px;">
      {% autoescape off %}
      {{post.content|linebreaksbr }}
      {% endautoescape %}
    </div>
  <br>
      {% if post.author == user %}
      <a href="{%url 'waterapp:post1_edit' pk=post.pk %}">
        <button type="button" class="btn btn-sm btn-success">수정</button>
      </a>
      <a href="{%url 'waterapp:post1_remove' pk=post.pk %}">
        <button type="button" class="btn btn-danger btn-sm ">삭제</button>
      </a>
      {% endif %}
      <a href="{% url 'waterapp:post1_list' %}">
        <button type="button" class="btn btn-info btn-sm">뒤로</button>
      </a>
    </div>

      <hr>

      <form class="" action="" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
          {% if form_edit %}
          {% else %}
            {% if user.is_anonymous %}
            <span class="comment-login-required"> 댓글 입력을 위해서는 <a href="{%url 'login' %}" class="login-link">로그인</a>이 필요합니다. </span>
            {% endif %}
          <button class="btn btn-default btn-sm comment-save" type="submit">저장</button>
          {% endif %}
      </form>

      {% for comment in post.comments.all %}
        {% if comment.id == pk %}
        <div class="comment">
          <form class="" action="" method="post">
            {% csrf_token %}
            <div class="comment-info">
                <strong>{{ comment.author }}</strong>
                <small>{{ comment.created_date | date:'Y-m-d H:i' }}</small>
                <button class="comment_save" type="submit"><img src="{% static 'bsr/img/edit.png' %}" class="comment_edit" alt="comment_edit_save"></button>
            </div>
              {{ form_edit }}
            </form>
        </div>
        <hr>
        {% else %}
        <div class="comment">
            <div class="comment-info">
                <strong>{{ comment.author }}</strong>
                <small>{{ comment.created_date | date:'Y-m-d H:i' }}</small>
                {% if comment.author == user %}
                <a href="{% url 'waterapp:comment1_edit' pk=comment.pk %}"><img class="comment1_edit" src="{% static 'bsr/img/edit.png' %}" alt=""></a>
                <a href="{% url 'waterapp:comment1_remove' pk=comment.pk %}"><img  class="comment1_remove" src="{% static 'bsr/img/delete.png' %}" alt=""></a>
                {% endif %}
            </div>
            {% autoescape off %}
            <p>{{ comment.text|linebreaks}}</p>
            {% endautoescape %}
        </div>
      </div>
      <hr>
      {% endif %}
    {% endfor %}
  </div>
 <footer id="gtco-footer" class="gtco-section" role="contentinfo">
      <div class="gtco-container">
        <div class="row row-pb-md">
          <div class="col-md-4 gtco-widget gtco-footer-paragraph">
            <h2 style="color: white">금수강산</h2>
            
          </div>
          <p style="color: white;">상 호 : 금강산수 | 대 표 자 : 홍명식  |  도 로 명  주 소  :  서 울 특 별 시  동 대 문 구  이 문 로 길  4 6 - 4 0<br>T E L  :  0 1 0 - 2 4 4 2 - 1 3 6 5  |  E m a i l  :  h o n g 1 4 0 0 @ n a t e . c o m</p>
        </div>
      </div>
      <div class="gtco-copyright">
        <div class="gtco-container">
          <div class="row">
            <div class="col-md-6 text-left">
              <p><small>&copy; 2018 금강산수. All Rights Reserved. </small></p>
            </div>

            <div class="col-md-6 text-right">
              <p><small>Designed by <a href="http://gettemplates.co/" target="_blank">GetTemplates.co</a> Demo Images: <a href="http://pixeden.com/" target="_blank">Pixeden</a> &amp; <a href="http://unsplash.com" target="_blank">Unsplash</a></small> </p>
            </div>
          </div>
        </div>
      </div>
    </footer>

  </div>

  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
  </div>
  
  <!-- jQuery -->
  <script src='{% static "js/jquery.min.js"%}'></script>
  <!-- jQuery Easing -->
  <script src='{% static "js/jquery.easing.1.3.js"%}'></script>
  <!-- Bootstrap -->
  <script src='{% static "js/bootstrap.min.js"%}'></script>
  <!-- Waypoints -->
  <script src='{% static "js/jquery.waypoints.min.js"%}'></script>
  <!-- Carousel -->
  <script src='{% static "js/owl.carousel.min.js"%}'></script>
  <!-- Main -->
  <script src='{% static "js/main.js"%}'></script>

  </body>
</html>